
networks:
  carmentis-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy:2
    container_name: carmentis-caddy
    restart: unless-stopped
    ports:
      - "80:80"        # HTTP
      - "443:443"      # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - carmentis-network
    depends_on:
      - node-cometbft
      - node-abci

  node-abci:
    container_name: carmentis-node-abci
    image: ghcr.io/carmentis/node/abci:testnet
    expose:
      - "26658"
    volumes:
      - ./cometbft:/cometbft
      - ./abci:/abci
      - ./abci-config.toml:/app/config.toml
    networks:
      - carmentis-network

  node-cometbft:
    container_name: carmentis-node-cometbft
    image: cometbft/cometbft:v1.x
    command:
      - start
      - --abci
      - grpc
      - --proxy_app
      - node-abci:26658
      - --rpc.laddr
      - tcp://0.0.0.0:26657
    depends_on:
      - node-abci
    ports:
      - 26656:26656
      - 26657:26657
    user: "1000"
    volumes:
      - ./cometbft:/cometbft
    networks:
      - carmentis-network
  
  operator-db:
    container_name: carmentis-operator-db
    image: postgres:15
    networks:
      - carmentis-network
    volumes:
      - ./operator-storage/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  operator-back:
    depends_on:
      - operator-db
    container_name: carmentis-operator-back
    image: ghcr.io/carmentis/operator/back:stable
    networks:
      - carmentis-network
    restart: always
    volumes:
      - ./operator-config.toml:/app/config.toml
      - ./operator-storage:/operator

  operator-front:
    container_name: carmentis-operator-front
    depends_on:
      - operator-back
    environment:
      - OPERATOR_URL=${OPERATOR_URL}
      - PORT=3000
    image: ghcr.io/carmentis/operator/front:stable
    networks:
      - carmentis-network
    restart: always

