networks:
  carmentis-network:
    driver: bridge
services:
  operator-back:
    container_name: ${ENV_TAG}-operator-back
    depends_on:
    - operator-db
    environment:
    - OPERATOR_DATABASE_NAME=${OPERATOR_POSTGRES_DB}
    - OPERATOR_DATABASE_USERNAME=${OPERATOR_POSTGRES_USER}
    - OPERATOR_DATABASE_PASSWORD=${OPERATOR_POSTGRES_PASSWORD}
    - OPERATOR_DATABASE_URL=operator-db
    - OPERATOR_DATABASE_PORT=5432
    - OPERATOR_DB_ENCRYPTION_KEY=${OPERATOR_DB_ENCRYPTION_KEY}
    - OPERATOR_KEYPAIR_FILE=/app/config/operator-keypair.json
    - OPERATOR_ADMIN_TOKEN_FILE=/app/config/operator-admin-token.txt
    - NODE_URL=${NODE_URL}
    - JWT_SECRET=${OPERATOR_JWT_SECRET}
    - PORT=3000
    image: ghcr.io/carmentis/operator/back:${ENV_TAG}
    networks:
    - carmentis-network
    ports:
    - 5001:3000
    restart: always
    volumes:
    - ${OPERATOR_KEYPAIR_FOLDER}:/app/config
  operator-db:
    container_name: ${ENV_TAG}-operator-postgres
    depends_on:
    - dev-node
    environment:
    - POSTGRES_USER=${OPERATOR_POSTGRES_USER}
    - POSTGRES_PASSWORD=${OPERATOR_POSTGRES_PASSWORD}
    - POSTGRES_DB=${OPERATOR_POSTGRES_DB}
    image: postgres:15
    networks:
    - carmentis-network
    ports:
    - 5555:5432
    restart: always
    volumes:
    - ./operator_db:/var/lib/postgresql/data
  operator-front:
    container_name: ${ENV_TAG}-operator-front
    depends_on:
    - operator-back
    environment:
    - OPERATOR_URL=${OPERATOR_URL}
    - PORT=3000
    image: ghcr.io/carmentis/operator/front:${ENV_TAG}
    ports:
    - 5002:3000
version: '3.3'
